### ISSUE TITLE
fusefs-gphotofs support ?

### ISSUE THREAD

**Issue by abishai** [vermaden/automount#13]
Is it possible to add fusefs-gphotofs to automount ? I use it to get photos from my camera and fusefs-simple-mtpfs is not working with it.
dsbmd supports it somehow.

**Comment by vermaden** [comment]
Maybe its possible, I assume that PTP will be used only when 'normal' filesystem or MTP will not be available?

**Comment by abishai** [comment]
I think so, as MTP is extension of PTP it's logical to try MTP first.

**Comment by vermaden** [comment]
There is already MTP support.
