### ISSUE TITLE
If Xorg not running, ${FM} is not started (different behaviour than prev. versions)

### ISSUE THREAD

**Issue by zwieblum** [vermaden/automount#14]
**Affected:** Version 1.7.0 on FreeBSD
**Sympton:** On a headless server or woekstation without Xorg running, ${FM} is not executed any more. Versions earlier did execute ${FM} regardless of Xorg running or not. 
**What should work:** call ${FM}, even if Xorg is not running.
**Code causing problem:** automount, the if-statement around "continue" in line 606.

**Comment by zwieblum** [comment]
Addition: The changes also render the ${USER} variable in the configfile useless, as ${FM} will not be run as ${USER}, but iterated over the all users of the specified users group. This can lead to "interesting" problems. 
Location: aoutomount, line 600 and following

**Comment by vermaden** [comment]
Thanks for this input. The 1.7 is generally re-thought of the whole idea of mounting. For example USER is not needed anymore and GROUP is used.


You can revert to old version by fetching the 1.6.1 version by hand:


`# fetch -o /usr/local/sbin/automount https://raw.githubusercontent.com/vermaden/automount/1.6.1/automount`


I did not had time recently to fix automount more, but I will have some free time after two weeks from now.


Regards.

**Comment by vermaden** [comment]
Version 1.7.1 brings back USER variable.
