### ISSUE TITLE
/dev/cd0: mount FAIL

### ISSUE THREAD

**Issue by digital-freak** [vermaden/automount#15]
On FreeBSD 12.0-STABLE r347422
```mount -t cd9660 -e -C=UTF-8 /dev/cd0 /media/cd0```
fails with `illegal option -- e` error

But
```mount -t cd9660 -o -e,-C=UTF-8 /dev/cd0 /media/cd0```
works fine

**Comment by vermaden** [comment]
Strange ... I am running 12.1-RELEASE and **man mount_cd9660** has this flag.

`     -e      Enable the use of extended attributes.`

... but I will remove it as it creates problems on other versions.

**Comment by vermaden** [comment]
Fixed in the GIT repo here:
https://github.com/vermaden/automount/blob/master/automount

As I just created 1.7.1 I will not yet create 1.7.2 port and wait a little for reports of other issues with 1.7.1 version.

But you can download and manually replace the **/usr/local/sbin/automount** to fix this problem.

Regards.

**Comment by vermaden** [comment]
... actually its a BUG in FreeBSD, BUG submitted here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242485

**Comment by digital-freak** [comment]
In fact, the man mount says that you can omit the `-o` flag, but this leads to an error:
```mount -t cd9660 -C = UTF-8 / dev / cd0 / media / cd0```
will say `mount: illegal option - C`

So only the option I cited works:
```mount -t cd9660 -o -e, -C = UTF-8 / dev / cd0 / media / cd0```

**Comment by digital-freak** [comment]
> Strange ... I am running 12.1-RELEASE and **man mount_cd9660** has this flag.
> 
> ` -e Enable the use of extended attributes.`
> 
> ... but I will remove it as it creates problems on other versions.

But you use the `mount` command, insted `mount_cd9660`

**Comment by vermaden** [comment]
The mount -t cd9660 command is an equivalent of mount_cd9660 command.

... but as I have been informed in the BUG report to make -e work I need to add -o before -e to make it work ... I will not comment that.

Regards.
