### ISSUE TITLE
Error when try to Mounting a Video DVD

### ISSUE THREAD

**Issue by dcschmid** [vermaden/automount#18]
Hi Vermaden,

thank you first for the great tool, you build. 

When i try to mount a Video DVD. I get the following error in the logs.
`2020-04-04 17:07:25 /dev/cd0: mount FAIL: 'mount -t cd9660 -e -C=UTF-8 /dev/cd0 /media/cd0'`

When i try to run that command i get this Error:

$ mount -t cd9660 -e -C=UTF-8 /dev/cd0 /media/cd0 
mount: illegal option -- e
usage: mount [-adflpruvw] [-F fstab] [-o options] [-t ufs | external_type]
       mount [-dfpruvw] special | node
       mount [-dfpruvw] [-o options] [-t ufs | external_type] special node`

Thanks for your help.

**Comment by digital-freak** [comment]
Look at issue #15 about this problem.
For fix it i just edit the filt `/usr/local/sbin/automount` on line 450 like this:
```FS_MOUNT_ARGS="-t cd9660 -o -e,-C=${ISO9660_CODEPAGE} ${DEV} ${MNT}"```

**Comment by vermaden** [comment]
Fixed along with several other things :)

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246026

Regards.
