### ISSUE TITLE
fusefs-ext4fuse port has expired

### ISSUE THREAD

**Issue by nicolashainaux** [vermaden/automount#20]
[https://www.freshports.org/sysutils/fusefs-ext4fuse/](https://www.freshports.org/sysutils/fusefs-ext4fuse/)

This removes ext4 support of automount (I simply cannot install sysutils/fusefs-ext4fuse).
Maybe it's possible to use fusefs-ext2 instead? (this is ext2, ext3 and ext4 read-write support).

**Comment by vermaden** [comment]
Fixed along with several other things :)

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246026

Regards.
