### ISSUE TITLE
Consider separating the change log from README

### ISSUE THREAD

**Issue by grahamperrin** [vermaden/automount#23]
From <https://github.com/vermaden/automount/issues/22#issuecomment-771049089>: 

```text
% automount --help
automount: illegal option -- -
usage: automount [-D name=value][-o opts][-Lcfuv]
% 
```

I ran `automount --help` because I saw it exemplified at the front page. 

https://github.com/vermaden/automount/blob/bf899bcbd5ecd992bdea703197c10951f54bbd90/README#L245

**Comment by vermaden** [comment]
I wrote that **README** before **/usr/sbin/automount** existed :)

**Comment by grahamperrin** [comment]
I understand :-) 

For newcomers, a short README (separated from the change log) could be better, including a brief hint on usage i.e.: 

`/usr/local/sbin/automount --help | less`

I'm happy to do a PR but I hesitate because you might prefer to write changes yourself …

**Comment by vermaden** [comment]
I will update the README :)

**Comment by grahamperrin** [comment]
Side note: I posted a comment under https://vermaden.wordpress.com/2018/10/11/freebsd-desktop-part-17-automount-removable-media/ (awaiting moderation) then noticed a typo, but the page will not allow me to post a corrected version of the comment: 

> Error: Please fill the required fields (name, email).

I used Google to sign in; those fields are not required. A non-cached reload of the page has not worked around the problem.

**Comment by vermaden** [comment]
GitHub has the same problem. Generally when You want to write new comment anywhere - first hit [CTRL]+[F5] to refresh the page without using your local cache.

I updated the README.

Regards.
