### ISSUE TITLE
Consider adding a trigger to format disks if they cannot be mounted

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#29]
Other operating systems ask the user whether the disk should be formatted in case a disk is attached the filesystem of which cannot be understood:

Classic Mac:

![image](https://user-images.githubusercontent.com/2480569/113918490-ca74fe00-97e2-11eb-82f3-f83f95e5f2b4.png)

Windows 10:

![image](https://user-images.githubusercontent.com/2480569/113918470-c3e68680-97e2-11eb-9dda-24e27a78bcb3.png)

I would like to implement something like this but for it to work the formatting tool would need to be notified by the automounter that a disk was attached the filesystem of which cannot be understood, and the `/dev/...` of that disk.

Ideally, the automounter would launch an executable like this:

`/usr/local/sbin/formattingtool /dev/da0`

with `/usr/local/sbin/formattingtool` being configurable.

The question is, what to do if the disk contains multiple partitions some of which can and some of which cannot be mounted. (In this case it should probably just report the non-mountable partitions?)

Or is there a better way to achieve this, e.g., using D-Bus? (Which seems complicated overkill to me.)

**Comment by vermaden** [comment]
Out of scope for **automount(8)**.
