### ISSUE TITLE
Files on FAT media not writable

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#38]
Using 30fc238, files on FAT media are missing the write bit: 

```
% mount | grep MONKEYPATCH
/dev/da1 on /media/MONKEYPATCH (msdosfs, local, noatime)

% ls -lh /media/MONKEYPATCH      
total 2048128
drwxrwxr-x  1 root  wheel    32K 16 Nov. 22:55 default
-rwxr-xr-x  1 root  wheel    33K 16 Nov. 23:07 default.tgz
```

Can you reproduce this issue?

**Comment by probonopd** [comment]
Related? https://github.com/vermaden/automount/issues/27

**Comment by vermaden** [comment]
That should help:
https://github.com/vermaden/automount/commit/3dacc130686bfc675144706f74af352b5f2b8149

**Comment by probonopd** [comment]
It does indeed :+1:  Again, thanks a ton.
