### ISSUE TITLE
Add an option to not automount ESP

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#39]
Now that internal drives are automouted it would be useful to have an option to not automount [EFI System Partition](https://en.wikipedia.org/wiki/EFI_system_partition) (ESP). 

The globally unique identifier (GUID) for the EFI system partition in the GUID Partition Table (GPT) scheme is `C12A7328-F81F-11D2-BA4B-00A0C93EC93B`.

**Comment by vermaden** [comment]
"I'm Afraid I Can't Do That, Dave." - to cite HAL.

The **automount(8)** is for automounting everything - it does not matter if its some EFI shit or your casual pendrive.

You can make fork of **automount(8)** into **automount-hello(8)** for example so you may tailor it to your needs - if that is needed.

**Comment by vermaden** [comment]
I though about it for some time and maybe adding such an option will not be that bad idea.

I will try to look into that - maybe that would prevent creating the **automount(8)** fork and maintaining two versions :)

**Comment by probonopd** [comment]
> maybe that would prevent creating the automount(8) fork and maintaining two versions :)

Yes, lets avoid that under any circumstance!

**Comment by probonopd** [comment]
The same should go for Microsoft Reserved Partition (MSR) partitions which have the GUID Partition Table (GPT) label `E3C9E316-0B5C-4DB8-817D-F92DF00215AE` according to https://en.wikipedia.org/wiki/Microsoft_Reserved_Partition.

Reference:
https://twitter.com/Sweordbora/status/1482830236706295811

**Comment by vermaden** [comment]
I am sorry it took so long ...

Added support to ignore EFI and MSR partitions in **automount(8)**.

Details:
https://github.com/vermaden/automount/commit/1b69cda21f4e31855f23c8864c1cfc052226816f

Just add **IGNORE_SYS_PARTS=YES** to the **/usr/local/etc/automount.conf** file.

Regards :)

**Comment by probonopd** [comment]
Great! :+1: Thank you very much @vermaden
