### ISSUE TITLE
REMOVEDIRS does not remove all /media dirs after unmount/unplug

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#40]
https://github.com/vermaden/automount/commit/2a1f2a29725165d7dc4c422849668546fab010da introduced `REMOVEDIRS`:

> REMOVEDIRS (set to YES by default)
  If set to YES the automount(8) will remove /media dir after unmount.

Apparently, this currently only works if `/usr/local/sbin/automount` is doing the unmounting.

If the user just unplugs the device or unmounts by hand, then the mount point is not removed.

This can lead to leftover empty mountpoints, which can be quite messy over time in `/media`. 
Could automount catch the respective devd messages and clean up the extraneous directories?

Thanks @decuser for pointing this out.

**Comment by vermaden** [comment]
I will look into that.

**Comment by vermaden** [comment]
I think that I fixed that one too.

Details:
https://github.com/vermaden/automount/commit/466712252a57ca0963a98880579714767d36c39d

Regards.

**Comment by probonopd** [comment]
Awesome! :+1: Thank you very much @vermaden
