### ISSUE TITLE
Increase timeout?

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#42]
Looks like my ebook reader needs more time:

```
2022-04-07 07:13:09 /dev/da0: attach
2022-04-07 07:13:10 /dev/da0: wait for device retry 1/3
2022-04-07 07:13:11 /dev/da0: wait for device retry 2/3
2022-04-07 07:13:11 /dev/da0: not a block device
```

Technically the ebook reader is an Android device which simulates a mass storage device, using `Linux File-CD Gadget`. So it probably just takes much longer than `automount` thinks.

When I mount it manually it works fine.
I think we'd just need to increase the timeout?

**Comment by vermaden** [comment]
Set `RETRY_DELAY=5` (or more) in your `/usr/local/etc/automount.conf` config.

**Comment by probonopd** [comment]
Sure enough, works.
Being a bit a "it just works" aficionado, would you consider making this the default?

**Comment by vermaden** [comment]
That is the first device I know to have this problem.

Fine the lowest working value of `RETRY_DELAY` and let me know please.

**Comment by probonopd** [comment]
Well, I only can tell for my device, but there are other models, too, including older/slower ones. Would it make sense to e.g., double the delay for each retry?

**Comment by vermaden** [comment]
Thanks. I will also increase the `RETRY_COUNT` value a little.

**Comment by vermaden** [comment]
Will be at that in next release:

```
: ${RETRY_COUNT='5'}                    # retry count
: ${RETRY_DELAY='2'}                    # retry delay time
```

**Comment by probonopd** [comment]
Thanks @vermaden

**Comment by vermaden** [comment]
Updated.

- https://twitter.com/vermaden/status/1694440196236849227
- https://bsd.network/@vermaden/110940718791974585
- https://mastodon.bsd.cafe/@vermaden/110940719515574245

Thanks.
