### ISSUE TITLE
More reliable cleanup

### ISSUE THREAD

**Issue by probonopd** [vermaden/automount#44]
Despite having `REMOVEDIRS="YES"` set in `/usr/local/etc/automount.conf`, I find that more often than not empty directories are left over in `/media`.

What do you think about using the following? I am using it with great success. It finds all empty directories in `/media` and deletes them in one step.

```
find /media -depth 1 -empty -prune -delete 2>/dev/null
```

**Comment by vermaden** [comment]
I will try that, thanks :)

**Comment by vermaden** [comment]
Updated.

- https://twitter.com/vermaden/status/1694440196236849227
- https://bsd.network/@vermaden/110940718791974585
- https://mastodon.bsd.cafe/@vermaden/110940719515574245

Thanks.
