### ISSUE TITLE
`automount` launch caja with German locale, while desktop's is English

### ISSUE THREAD

**Issue by lispstudent** [vermaden/automount#45]
Hello,

I have an unusual situation, perhaps only loosely related to `automount`.  I have this in my  `/usr/local/etc/automount.conf`:

```
FM="caja --browser --no-desktop"
```

When I connect a USB drive, `caja` is launched with German locale and different settings.

If I launch `caja` from the taskbar, though, it has my defined English locale.

Is by any chance `automount` using a different locale?  How could one debug this kind of issues?

See attached screenshots.

![20221212-01](https://user-images.githubusercontent.com/59874114/206984504-46b1821f-7e28-40a9-a1f9-2ef844075d1e.png)

![20221212-03](https://user-images.githubusercontent.com/59874114/206984520-d4b1cbb0-0d31-47a8-a4e8-882a1468e0ec.png)

**Comment by vermaden** [comment]
Hi,

its the first time I have heard about such issue - but for a start I would out that line below into the **/usr/local/etc/automount.conf** file:

```
FM="env LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 caja --browser --no-desktop"
```

Please do that and let me know if it helped.

Thanks,
vermaden

**Comment by lispstudent** [comment]
Yes, with that line, `caja` opens with proper English locale.

Thank you for the help!

**Comment by vermaden** [comment]
Glad to hear that :)

Regards.
