### ISSUE TITLE
Call for testing

### ISSUE THREAD

**Issue by outpaddling** [vermaden/automount#49]
I've created two new tools as companions for automount:
NPMount is an suid command-line tool that allows non-privileged users to mount and unmount only certain mount points, configured in $PREFIX/etc/npmount.conf.  Users must be a member of a specific group bound to a globbing pattern for mount points.  The default config is as follows, which should work for most FreeBSD users:
```
# Group     Mount points
operator    /media/*
```
[https://github.com/outpaddling/npmount](https://github.com/outpaddling/npmount)

QMediaManager is a graphical tool invoked by automount that presents the user with options to open a file manager, unmount, or reformat the media.  It uses npmount for the unmount option and can be configured to run any file manager.  By default, it looks for any of a list of common file managers available in FreeBSD ports.
![Screenshot-2023-06-05-15-19-30](https://github.com/vermaden/automount/assets/11299711/48408e55-a796-4697-98d1-f2593b661355)

[https://github.com/outpaddling/qmediamanager](https://github.com/outpaddling/qmediamanager)

To test, follow the instructions to install freebsd-ports-wip here:
[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

Then run `wip-reinstall-port qmediamanager` and add the following to /usr/local/etc/automount.conf:

```
FM=/usr/local/bin/qmediamanager
```

**Comment by vermaden** [comment]
I am sorry ... I overlooked your proposal ... for way too long.

As I have a moment to 'take care' ot `automount(8)` I will also try to mention this one.

Thanks.

**Comment by vermaden** [comment]
Hi,

I just wanted to test **qmediamanger** a little - but it has a dependency on stuff that 'conflicts' with **automount(8)**.

Not sure how to cope with that (besides forcefully installing without needed deps).


```
# pkg install deskutils/qmediamanager
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 5 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        auto-admin: 0.8.0
        devd-mount: 0.1.0.7
        libxtend: 0.1.9
        npmount: 0.1.1
        qmediamanager: 0.1.1_1

Number of packages to be installed: 5

241 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/5] Fetching auto-admin-0.8.0.pkg: 100%  104 KiB 106.3kB/s    00:01    
[2/5] Fetching npmount-0.1.1.pkg: 100%   12 KiB  11.8kB/s    00:01    
[3/5] Fetching devd-mount-0.1.0.7.pkg: 100%    7 KiB   6.7kB/s    00:01    
[4/5] Fetching qmediamanager-0.1.1_1.pkg: 100%   20 KiB  20.9kB/s    00:01    
[5/5] Fetching libxtend-0.1.9.pkg: 100%   99 KiB 101.4kB/s    00:01    
Checking integrity... done (1 conflicting)
  - devd-mount-0.1.0.7 conflicts with automount-1.7.9 on /usr/local/sbin/automount
Checking integrity... done (0 conflicting)
Conflicts with the existing packages have been found.
One more solver iteration is needed to resolve them.
The following 6 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
        automount: 1.7.9

New packages to be INSTALLED:
        auto-admin: 0.8.0
        devd-mount: 0.1.0.7
        libxtend: 0.1.9
        npmount: 0.1.1
        qmediamanager: 0.1.1_1

Number of packages to be removed: 1
Number of packages to be installed: 5

Proceed with this action? [y/N]: n
```

**Comment by outpaddling** [comment]
QMediaManager is now hardwired to work with devd-mount rather than automount.  Originally, devd-mount was linked to automount so it could be used as a drop-in replacement for automount, but I don't think I will continue to support this.  I've removed the automount link from the latest WIP devd-mount, so it will no longer conflict.  I'll commit to the ports tree after reasonable testing.

**Comment by vermaden** [comment]
OK. Thank You.
