### ISSUE TITLE
DISPLAY incorrectly detected on FreeBSD 12.4 running SDDM

### ISSUE THREAD

**Issue by outpaddling** [vermaden/automount#50]
The automount script parses output of procstat pargs $(pgrep Xorg), taking the value of argv[1] as the X11 display.  On this system, it ends up with DISPLAY_ID="-nolisten".  As a result, it mounts the media successfully, but cannot launch $FM.

procstat output:

FUSE exfat 1.4.0 (libfuse2)                                                     
1518:  Xorg                                                                     
argv[0]: /usr/local/libexec/Xorg                                                
argv[1]: -nolisten                                                              
argv[2]: tcp                                                                    
argv[3]: -auth                                                                  
argv[4]: /var/run/sddm/{5bea390f-28f5-416e-8db8-7d80d8db784b}                   
argv[5]: -background                                                            
argv[6]: none                                                                   
argv[7]: -noreset                                                               
argv[8]: -displayfd                                                             
argv[9]: 20                                                                     
argv[10]: -seat                                                                 
argv[11]: seat0                                                                 
argv[12]: vt9

**Comment by vermaden** [comment]
Updated.

- https://twitter.com/vermaden/status/1694440196236849227
- https://bsd.network/@vermaden/110940718791974585
- https://mastodon.bsd.cafe/@vermaden/110940719515574245

Thanks.
