### ISSUE TITLE
kernel module fuse

### ISSUE THREAD

**Issue by lherschi** [vermaden/automount#52]
"kldload fuse" in automount line 508 can be removed. In FreeBSD 12.4, fuse.ko was already a link to fusefs.ko. In FreeBSD 13.2 there is only fusefs.ko.

**Comment by vermaden** [comment]
Yes. I know this is future thinking (no longer needed) but it does not hurts and there are some cases when someone needs to run `automount(8)` on older system - so this (pointless now) command of loading `fuse.ko` does not hurt and may be useful for someone :)

Thank You for the report tho.

Regards,
ver

**Comment by lherschi** [comment]
On systems on which both fusefs and fuse are present (e.g. FreeBSD 12.4 has a link fuse on fusefs), the following message appears on startup, which is unpleasant.

interface fusefs.1 already present in the KLD 'fusefs.ko'!
linker_load_file: /boot/kernel/fuse.ko - unsupported file type

**Comment by vermaden** [comment]
Is this message in 'white' font - directly from the kernel?

**Comment by vermaden** [comment]
I just checked right now - and FreeBSD 12.x (in any version) is EOL since 2023/12:

- https://freebsd.org/releases/

So I believe focusing on it now seems like a waste of time ... what You think?

**Comment by lherschi** [comment]
Yes, but FreeBSD 12.4 was at least the last FreeBSD that still had fuse. All after that have fusefs. That's why I said fuse could be abolished.

**Comment by lherschi** [comment]
Thank you.

**Comment by vermaden** [comment]
Thanks.
