### ISSUE TITLE
Repository does not include license file

### ISSUE THREAD

**Issue by yarwelp** [vermaden/automount#9]
Hello, I saw that the automount script has a license notice in it. However, for the repository itself, no license file is included. In order to properly declare the license conditions that apply to the remainder of the files within the repository, please create a license file in the root of the repository so that there can be no doubt.

It's a nice project and I would like to make use of it :)

**Comment by vermaden** [comment]
BSD License is in the `automount` file:

- https://github.com/vermaden/automount/blob/539a0ac32b50cc4b20427a18e04c4b061bc5da09/automount#L7
